---
title: "P8105_hw1_xh2470"
author: "Xueqing Huang UNI:xh2470"
output: github_document
---

# Problem 1

```{r problem 1}

library(tidyverse)

df = tibble(
  vec_numeric = rnorm(10),
  vec_logical = vec_numeric > 0,
  vec_char = c("My", "Name", "is", "Xueqing", "Huang", "and", "my", "UNI", "is", "xh2470"),
  vec_factor = factor(c("poor", "good", "poor", "perfect", "good", "poor", "perfect", "perfect", "poor", "good"))
)

# calculate mean of the above variables.
mean(pull(df, vec_numeric))
mean(pull(df, vec_logical))
mean(pull(df, vec_char))
mean(pull(df, vec_factor))
```

```{r convert variables, eval = FALSE}

# convert variables

as.numeric(pull(df, vec_logical))
as.numeric(pull(df, vec_char))
as.numeric(pull(df, vec_factor))

# We can calculate the mean of only numeric and logical variables.

```

# Problem 2
```{r load dataset}
data("penguins", package = "palmerpenguins")
```

The name of the dataset is **penguins**, and it contains **`r nrow(penguins)`** rows and **`r ncol(penguins)`** columns.
Variables of this dataset include _`r names(penguins)`_.

**Value of the variables**

```{r}
summary(penguins)
```

**Mean of flipper length**

`r mean(pull(penguins, flipper_length_mm), na.rm = TRUE)`

```{r scatterplot}
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm)) + geom_point(aes(colour = species))

ggsave("scatter_plot.pdf", height = 4, width = 6)

```

